spring:
  profiles:
    active: local
server:
  port: 8091

---
spring:
  profiles: local
  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094  # all kafka brokers addresses
      key-serializer: org.apache.kafka.common.serialization.IntegerDeserializer # coz libraryEventId is integer in LibraryEvent
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer # coz Book is a json string.
      group-id: library-events-listener-group

---

spring:
  profiles: dev
  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group

---

spring:
  profiles: prod
  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group